#Whether to enable update detection
update: true
#Whether to enable the function of this plug-in
skip: true
#Set how many people to sleep and skip the night
skipNum: 1
#Total percentage of people sleeping,The best percentage is 25% 50% 75% 100%
skipPet: 50
#skip mode pet num
model: 'num'