#Whether to enable update detection
update: true
#Whether to enable the function of this plugin
skip: true
#Set how many people to sleep and skip the night
skipNum: 1
#Total percentage of people sleeping,The best percentage is 25% 50% 75%
skipPet: 50
#skip mode pet num
model: 'num'

#Select your language
Language:
  #Without your language
  #You can create your own language file
  #1.Copy one of the language files
  #2.Change its name (you can change it without any requirement)
  #3.Set the lang option to the created Lang file
  #4.Change the Messages in the lang file
  lang: chinese