name: SkipSleep
version: 1.5.0
main: com.skipsleep.SkipSleep
author: 'PlaidMrdeer'
website: 'https://www.spigotmc.org/resources/skipsleep.106146/'
description: 'A lightweight plug-in that only needs one person to sleep and can skip the night'
api-version: 1.13
commands:
  sks:
    description: 'Main command'